P:
  START:
    - "8:40"
    - "10:10"
    - "12:15"
    - "13:45"
    - "15:15"
    - "16:45"
  END:
    - "9:55"
    - "11:25"
    - "13:30"
    - "15:00"
    - "16:30"
    - "18:00"
TERM:
  # 学年暦 ref 学群
  # http://www.tsukuba.ac.jp/campuslife/calendar/
  # https://www.tsukuba.ac.jp/admission/auditors/pdf/gun_3.pdf
  BEGIN:
    春:
      A: 2018/04/12
      B: 2018/05/22
      C: 2018/07/03
    夏: 2018/08/09
    秋:
      A: 2018/10/01
      B: 2018/11/08
      C: 2019/01/07
  # 13:00 となっているのは、GMTで指定するため (JSTなら、22:00)
  END:
    春:
      A: 2018/05/21 13:00
      B: 2018/06/25 13:00
      C: 2018/08/07 13:00
    夏: 2018/09/30 13:00
    秋:
      A: 2018/11/07 13:00
      B: 2018/12/19 13:00
      C: 2019/02/14 13:00
database:
  filename: "kamoku.db"
  table_name: "kamoku"
  column_names:
    - "code"
    - "name"
    - "method"
    - "unit"
    - "grade"
    - "term"
    - "period"
    - "location"
    - "teacher"
    - "abstruct"
    - "note"
    - "research_students"
    - "reason"
    - "english_name"
    - "time"
